name: Test

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
    - run: yarn
    - run: yarn test
      env:
        CI: true
